#!/bin/bash
echo "欢迎使用一键搭建"
echo "即将搭建的是4.26-5.10版本"
echo "准备开始安装"
read -p "回车后开始安装"
echo "请输入你的内网ip" 
read -p "内网ip： " ip
cp /root/pubgradar/restart.sh /root/restart.sh
chmod +x restart.sh

git clone https://github.com/794959818/pubgradar.git
cd pubgradar/
npm i
npm i -g pino
npm install -g forever
forever start index.js sniff eth0 $ip | pino

echo "搭建完成"
